### PR TITLE
added threading

### PR DESCRIPTION
**Pull request by kronicd**
I added threading and a new option to control the number of threads. In testing I was able to run 10 threads without issue. It may go higher.

### CODE REVIEW

**Comment by bka-dev** [comment]
Thanks a lot. During initial development I thought about including threading as well but had a few occasions where I ran into some rate-limiting of the Teams APIs. I'll do some testing with some of my lists and different amounts of threads. Happy to merge it afterwards

**Comment by kronicd** [comment]
Interesting, so I've been able to run with 100 threads and a delay of 0. No errors so far.

I wonder how the rate limiting is determined. Keen to see the result of your testing.

**Review by bka-dev — DISMISSED** [review]
Looks good. Like in your tests I ran through a list of 1000 users with up to 100 threads and had no occasions of rate limiting. Not sure how they implemented it.

**Review by bka-dev — APPROVED** [review]
also increased minor version and added changelog

**Pull request merged**
